apiVersion: app/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
    containers:
      - name: prometheus
        image: prom/prometheus:v2.2.1
        args:
        - --config.file=/mnt/etc/prometheus.yml
        - --storage.tsdb.retention=24h
        - --web.external-url=$(EXTERNAL_URL)/prometheus
        ports:
        - containerPort: 9090
        env:
        - name: EXTERNAL_URL
          valueFrom:
            configMapKeyRef:
              name: external-url
              key: url
        volumeMounts:
        - name: config-volume
          mountPath: /mnt/etc/
        - name: data-volume
          mountPath: /mnt/data/
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      - name: data-volume
        emptyDir: {}