kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: all-reader
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - 'get'
  - 'watch'
  - 'list'
- nonResourceURLs:
  - '*'
  verbs:
  - 'get'
