apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: nginx-dr
  namespace: default
spec:
  host: nginx-svc.sample-ns.svc.cluster.local
  subsets:
  - name: blue
    labels:
      version: blue
  - name: green
    labels:
      version: green
