kind: ConfigMap
apiVersion: v1
data:
  containers.input.conf: |-
    <source>
      type tail
      format json
      time_key time
      path /var/log/containers/*.log
      pos_file /var/log/gcp-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%N%Z
      tag reform.*
      read_from_head true
    </source>

    <match reform.**>
      @type record_reformer
      enable_ruby true
      tag raw.kubernetes.${tag_suffix[4].split('-')[0..-2].join('-')}
    </match>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @type copy

      <store>
        @type detect_exceptions

        remove_tag_prefix raw
        message log
        multiline_flush_interval 5
        max_bytes 500000
        max_lines 1000
      </store>
    </match>
  containers.output.conf: |-
    <match kubernetes.**>
      @type bigquery

      method insert

      auth_method json_key
      json_key {"private_key": "xxxx", "client_email": "xxxx"}

      project xxxx
      dataset kubernetes
      table logs

      schema [
        { "name": "log", "type": "STRING" },
        { "name": "stream", "type": "STRING" }
      ]
    </match>
metadata:
  name: fluentd-gcp-config
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
